version: "3"

services:
  mosquitto:
    build: .
    image: registry.beuth-hochschule.de/iisy/mosquitto:0.0.1
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
